//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindIt.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class persona
    {
        [DisplayName("Cedula")]
        public string idPersona { get; set; }
        [DisplayName("Nombre")]
        public string nombre { get; set; }
        [DisplayName("Telefono")]
        public string telefono { get; set; }
        [DisplayName("Email")]
        public string email { get; set; }
        [DisplayName("User Name")]
        [Required(ErrorMessage = "This field is required")]
        public string usuario { get; set; }
        [DisplayName("Password")]
        [Required(ErrorMessage = "This field is required")]
        public string pass { get; set; }
        [DisplayName("Empresa")]
        public bool tipo { get; set; }
        [DisplayName("Error")]
        public string LoginErrorMessage { get; set; }
    }
}
